### ISSUE TITLE
swagger-ui 2.1.4 compatibility

### ISSUE THREAD

**Issue by john-kurkowski** [rynam0/ember-swagger-ui#7] opened 2016-01-08 01:30 UTC
Getting ENOENT due to missing resources hardcoded in ember-swagger-ui's build. For example, [these fonts](https://github.com/rynam0/ember-swagger-ui/blob/0.0.16/index.js#L10-L19) do not exist in swagger-ui 2.1.4.

The folder structure seems to be the same, so maybe the lib can do something like `cp path/to/fonts/* dist/fonts/`?

**Comment by rynam0** [comment] 2016-01-08 13:55
Thanks for reporting, @john-kurkowski!  I am seeing this in my project's CI build and will take a look into this as soon as I get a chance.

**Comment by rynam0** [comment] 2016-01-09 19:37
FWIW: I locked down the swagger-ui dependency in my consuming application's bower.json file to version 2.1.3 to get around the issue.  I'm still looking into how we might handle this in the addon  package's index.js file as much has changed from 2.1.3 to 2.1.4 in regards to the files they produce in the distribution. IMO, they probably should have incremented to 2.2.0 to reflect the new functionality (json editor for one) and not changed the names of the font files in a patch release.  I'm also fairly certain that by design, the ember application api doesn't support importing a directory.   I'll look into this a bit more but I think we may just have to lock down the swagger-ui dependency version to 2.1.4 for this one.

**Comment by rynam0** [comment] 2016-01-11 15:20
ember-swagger-ui@0.0.17 locks down the swagger-ui version to 2.1.3 while ember-swagger-ui@0.0.18 locks down the swagger-ui version to 2.1.4.

**Comment by rynam0** [comment] 2016-01-11 17:26
Reopening due to #8.

**Comment by rynam0** [comment] 2016-10-21 20:48
Closing as #31 has been merged.

**Closed by rynam0** 2016-10-21 20:48 UTC
